version: "3"
services:
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: reactive_spring_data_jdbc
    ports:
      - 5432:5432