version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
#  oracledb:
#    image: store/oracle/database-enterprise:12.2.0.1
#    hostname: oracledb
#    ports:
#    - 1521:1521
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ptest
      POSTGRES_USER: ptest
      POSTGRES_DB: ptest
    ports:
    - 5432:5432
  redis-in-hibernate:
    image: docker.io/devbhuwan/redis-in-hibernate
    build:
      context: ./redis-in-hibernate
      dockerfile: Dockerfile
      args:
      - JAR_FILE=target/redis-in-hibernate.jar
    ports:
    - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: postgres, redis
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ptest
      SPRING_DATASOURCE_USERNAME: ptest
      SPRING_DATASOURCE_PASSWORD: ptest
    links:
      - redis
      - postgres

