version: "3"
services:
  spring-boot-oracle-db-in-kubernetes:
    image: devbhuwan/spring-boot-oracle-db-in-kubernetes:v1
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - JAR_FILE=build/libs/spring-boot-oracle-db-in-kubernetes-0.0.1-SNAPSHOT.jar
    ports:
    - 8080
    restart: always