workflows:
  version: 2
  build-deploy:
    jobs:
      - unit-test
      - publish-docker:
          requires:
            - unit-test
          filters:
            branches:
              only: master

version: 2
jobs:
  unit-test:
    docker:
      - image: maven:3.6.0-jdk-8-alpine
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - hello-spring-mvn-V2-{{ checksum "springboot-order-crud-service/pom.xml" }}
            - hello-spring-mvn-V2
      - run: mvn -f springboot-order-crud-service/pom.xml dependency:go-offline
      - run:
          name: Build and unit test
          command: |
            mvn -f springboot-order-crud-service/pom.xml test -B \
              -Dbuild.number=${CIRCLE_BUILD_NUM} \
              -Dcommit.hash=${CIRCLE_SHA1} \
              -Dcircle.workflow.guid=${CIRCLE_WORKFLOW_ID} \
              -Dbuild.user=${CIRCLE_PROJECT_USERNAME} \
              -Dbuild.repo=${CIRCLE_PROJECT_REPONAME} 
      - save_cache:
          paths:
            - ~/.m2
          key: hello-spring-mvn-V2-{{ checksum "springboot-order-crud-service/pom.xml" }}
      - store_test_results:
          path: target/surefire-reports

  publish-docker:
    docker:
      - image: maven:3.6.0-jdk-8-alpine
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - hello-spring-mvn-V2-{{ checksum "springboot-order-crud-service/pom.xml" }}
            - hello-spring-mvn-V2
      - run: mvn -f springboot-order-crud-service/pom.xml dependency:go-offline
      - run:
          name: Publish Docker image with Jib
          command: |
            cd springboot-order-crud-service && \
            ./mvnw package com.google.cloud.tools:jib-maven-plugin:0.10.0:dockerBuild -Dimage=docker.io/devbhuwan/order-service:latest
              -Dbuild.number=${CIRCLE_BUILD_NUM} \
              -Dcommit.hash=${CIRCLE_SHA1} \
              -Dcircle.workflow.guid=${CIRCLE_WORKFLOW_ID} \
              -Dbuild.user=${CIRCLE_PROJECT_USERNAME} \
              -Dbuild.repo=${CIRCLE_PROJECT_REPONAME} 